stages:
    - test
image: pennlabs/tox

python37:
    stage: test
    script: tox -e py37

check:
    stage: test
    script: tox -e check

spell:
    stage: test
    script: tox -e spell

docs:
    stage: test
    script: tox -e docs

report:
    stage: test
    script: tox -e dogfood
